//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.svc_Cat_Mat_PL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svc_Cat_Mat_PL.ILetsGo_Interface")]
    public interface ILetsGo_Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/ListarDatos", ReplyAction="http://tempuri.org/ILetsGo_Interface/ListarDatosResponse")]
        PL.svc_Cat_Mat_PL.ListarDatosResponse ListarDatos(PL.svc_Cat_Mat_PL.ListarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/ListarDatos", ReplyAction="http://tempuri.org/ILetsGo_Interface/ListarDatosResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.ListarDatosResponse> ListarDatosAsync(PL.svc_Cat_Mat_PL.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/FiltrarDatos", ReplyAction="http://tempuri.org/ILetsGo_Interface/FiltrarDatosResponse")]
        PL.svc_Cat_Mat_PL.FiltrarDatosResponse FiltrarDatos(PL.svc_Cat_Mat_PL.FiltrarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/FiltrarDatos", ReplyAction="http://tempuri.org/ILetsGo_Interface/FiltrarDatosResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.FiltrarDatosResponse> FiltrarDatosAsync(PL.svc_Cat_Mat_PL.FiltrarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Insertar_DatosSinIdentity", ReplyAction="http://tempuri.org/ILetsGo_Interface/Insertar_DatosSinIdentityResponse")]
        PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityResponse Insertar_DatosSinIdentity(PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Insertar_DatosSinIdentity", ReplyAction="http://tempuri.org/ILetsGo_Interface/Insertar_DatosSinIdentityResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityResponse> Insertar_DatosSinIdentityAsync(PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Insertar_DatosConIdentity", ReplyAction="http://tempuri.org/ILetsGo_Interface/Insertar_DatosConIdentityResponse")]
        PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityResponse Insertar_DatosConIdentity(PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Insertar_DatosConIdentity", ReplyAction="http://tempuri.org/ILetsGo_Interface/Insertar_DatosConIdentityResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityResponse> Insertar_DatosConIdentityAsync(PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Modifica_Datos", ReplyAction="http://tempuri.org/ILetsGo_Interface/Modifica_DatosResponse")]
        PL.svc_Cat_Mat_PL.Modifica_DatosResponse Modifica_Datos(PL.svc_Cat_Mat_PL.Modifica_DatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Modifica_Datos", ReplyAction="http://tempuri.org/ILetsGo_Interface/Modifica_DatosResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Modifica_DatosResponse> Modifica_DatosAsync(PL.svc_Cat_Mat_PL.Modifica_DatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Elimina_Datos", ReplyAction="http://tempuri.org/ILetsGo_Interface/Elimina_DatosResponse")]
        PL.svc_Cat_Mat_PL.Elimina_DatosResponse Elimina_Datos(PL.svc_Cat_Mat_PL.Elimina_DatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGo_Interface/Elimina_Datos", ReplyAction="http://tempuri.org/ILetsGo_Interface/Elimina_DatosResponse")]
        System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Elimina_DatosResponse> Elimina_DatosAsync(PL.svc_Cat_Mat_PL.Elimina_DatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNombreSP, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string sMsjError) {
            this.ListarDatosResult = ListarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.SqlDbType DbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sValorParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sMsjError;
        
        public FiltrarDatosRequest() {
        }
        
        public FiltrarDatosRequest(string sNombreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sNombreParametro = sNombreParametro;
            this.DbType = DbType;
            this.sValorParametro = sValorParametro;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable FiltrarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public FiltrarDatosResponse() {
        }
        
        public FiltrarDatosResponse(System.Data.DataTable FiltrarDatosResult, string sMsjError) {
            this.FiltrarDatosResult = FiltrarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosSinIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosSinIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Insertar_DatosSinIdentityRequest() {
        }
        
        public Insertar_DatosSinIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosSinIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosSinIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Insertar_DatosSinIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Insertar_DatosSinIdentityResponse() {
        }
        
        public Insertar_DatosSinIdentityResponse(bool Insertar_DatosSinIdentityResult, string sMsjError) {
            this.Insertar_DatosSinIdentityResult = Insertar_DatosSinIdentityResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosConIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosConIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sMsjError;
        
        public Insertar_DatosConIdentityRequest() {
        }
        
        public Insertar_DatosConIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string sValorScalar, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.sValorScalar = sValorScalar;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosConIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosConIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Insertar_DatosConIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Insertar_DatosConIdentityResponse() {
        }
        
        public Insertar_DatosConIdentityResponse(string Insertar_DatosConIdentityResult, string sValorScalar, string sMsjError) {
            this.Insertar_DatosConIdentityResult = Insertar_DatosConIdentityResult;
            this.sValorScalar = sValorScalar;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Modifica_DatosRequest() {
        }
        
        public Modifica_DatosRequest(string sNombreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Modifica_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Modifica_DatosResponse() {
        }
        
        public Modifica_DatosResponse(bool Modifica_DatosResult, string sMsjError) {
            this.Modifica_DatosResult = Modifica_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elimina_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Elimina_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Elimina_DatosRequest() {
        }
        
        public Elimina_DatosRequest(string sNombreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elimina_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Elimina_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Elimina_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Elimina_DatosResponse() {
        }
        
        public Elimina_DatosResponse(bool Elimina_DatosResult, string sMsjError) {
            this.Elimina_DatosResult = Elimina_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILetsGo_InterfaceChannel : PL.svc_Cat_Mat_PL.ILetsGo_Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LetsGo_InterfaceClient : System.ServiceModel.ClientBase<PL.svc_Cat_Mat_PL.ILetsGo_Interface>, PL.svc_Cat_Mat_PL.ILetsGo_Interface {
        
        public LetsGo_InterfaceClient() {
        }
        
        public LetsGo_InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LetsGo_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetsGo_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetsGo_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.ListarDatosResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.ListarDatos(PL.svc_Cat_Mat_PL.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNombreSP, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.ListarDatosRequest inValue = new PL.svc_Cat_Mat_PL.ListarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.ListarDatosResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).ListarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.ListarDatosResponse> ListarDatosAsync(PL.svc_Cat_Mat_PL.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.FiltrarDatosResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.FiltrarDatos(PL.svc_Cat_Mat_PL.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatos(request);
        }
        
        public System.Data.DataTable FiltrarDatos(string sNombreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.FiltrarDatosRequest inValue = new PL.svc_Cat_Mat_PL.FiltrarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreParametro = sNombreParametro;
            inValue.DbType = DbType;
            inValue.sValorParametro = sValorParametro;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.FiltrarDatosResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).FiltrarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.FiltrarDatosResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.FiltrarDatosResponse> FiltrarDatosAsync(PL.svc_Cat_Mat_PL.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.Insertar_DatosSinIdentity(PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest request) {
            return base.Channel.Insertar_DatosSinIdentity(request);
        }
        
        public bool Insertar_DatosSinIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest inValue = new PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).Insertar_DatosSinIdentity(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Insertar_DatosSinIdentityResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityResponse> Insertar_DatosSinIdentityAsync(PL.svc_Cat_Mat_PL.Insertar_DatosSinIdentityRequest request) {
            return base.Channel.Insertar_DatosSinIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.Insertar_DatosConIdentity(PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest request) {
            return base.Channel.Insertar_DatosConIdentity(request);
        }
        
        public string Insertar_DatosConIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string sValorScalar, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest inValue = new PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.sValorScalar = sValorScalar;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).Insertar_DatosConIdentity(inValue);
            sValorScalar = retVal.sValorScalar;
            sMsjError = retVal.sMsjError;
            return retVal.Insertar_DatosConIdentityResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityResponse> Insertar_DatosConIdentityAsync(PL.svc_Cat_Mat_PL.Insertar_DatosConIdentityRequest request) {
            return base.Channel.Insertar_DatosConIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.Modifica_DatosResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.Modifica_Datos(PL.svc_Cat_Mat_PL.Modifica_DatosRequest request) {
            return base.Channel.Modifica_Datos(request);
        }
        
        public bool Modifica_Datos(string sNombreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.Modifica_DatosRequest inValue = new PL.svc_Cat_Mat_PL.Modifica_DatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.Modifica_DatosResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).Modifica_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Modifica_DatosResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Modifica_DatosResponse> Modifica_DatosAsync(PL.svc_Cat_Mat_PL.Modifica_DatosRequest request) {
            return base.Channel.Modifica_DatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PL.svc_Cat_Mat_PL.Elimina_DatosResponse PL.svc_Cat_Mat_PL.ILetsGo_Interface.Elimina_Datos(PL.svc_Cat_Mat_PL.Elimina_DatosRequest request) {
            return base.Channel.Elimina_Datos(request);
        }
        
        public bool Elimina_Datos(string sNombreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            PL.svc_Cat_Mat_PL.Elimina_DatosRequest inValue = new PL.svc_Cat_Mat_PL.Elimina_DatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            PL.svc_Cat_Mat_PL.Elimina_DatosResponse retVal = ((PL.svc_Cat_Mat_PL.ILetsGo_Interface)(this)).Elimina_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Elimina_DatosResult;
        }
        
        public System.Threading.Tasks.Task<PL.svc_Cat_Mat_PL.Elimina_DatosResponse> Elimina_DatosAsync(PL.svc_Cat_Mat_PL.Elimina_DatosRequest request) {
            return base.Channel.Elimina_DatosAsync(request);
        }
    }
}
